/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: (typeof import('element-plus/es'))['ElAvatar']
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElCheckbox: (typeof import('element-plus/es'))['ElCheckbox']
    ElCollapse: (typeof import('element-plus/es'))['ElCollapse']
    ElCollapseItem: (typeof import('element-plus/es'))['ElCollapseItem']
    ElDialog: (typeof import('element-plus/es'))['ElDialog']
    ElForm: (typeof import('element-plus/es'))['ElForm']
    ElFormItem: (typeof import('element-plus/es'))['ElFormItem']
    ElInput: (typeof import('element-plus/es'))['ElInput']
    ElMenu: (typeof import('element-plus/es'))['ElMenu']
    ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem']
    ElMessage: (typeof import('element-plus/es'))['ElMessage']
    ElOption: (typeof import('element-plus/es'))['ElOption']
    ElPagination: (typeof import('element-plus/es'))['ElPagination']
    ElSelect: (typeof import('element-plus/es'))['ElSelect']
    ElTable: (typeof import('element-plus/es'))['ElTable']
    ElTableColumn: (typeof import('element-plus/es'))['ElTableColumn']
    ElTabPane: (typeof import('element-plus/es'))['ElTabPane']
    ElTabs: (typeof import('element-plus/es'))['ElTabs']
    ElTag: (typeof import('element-plus/es'))['ElTag']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    SvgIcon: (typeof import('./src/components/svgIcon/index.vue'))['default']
    Tabs: (typeof import('./src/components/tabs/index.vue'))['default']
  }
}
